version: "3.8"

services:
  bff:
    image: "kuratovia/pokedex-bff"
    restart: unless-stopped
    ports:
      - "49160:8080"
  front:
    image: "kuratovia/pokedex-front"
    restart: unless-stopped
    ports:
      - "8080:8080"
