name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_VUE_APP_BASE_URI: ${{ secrets.ENV_KEY }}
          directory: ./front

      - name: Copy docker-compose
        run: |
          mkdir test
          cp docker-compose.yml /test/docker-compose.yml

      - name: Build and push images
        run: |
          docker build -f ./front/Dockerfile ./front -t ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-front
          docker build -f ./bff/Dockerfile ./bff -t ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-bff
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-front
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-bff
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Copy docker.compose.yml to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: test/docker-compose.yml
          remote: test/docker-compose.yml
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          run: mv -f docker-compose.yml
          script: |
            docker-compose up