name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Copy .env
        run: cp $dev ./front/.env

      - name: Build front image
        run: docker build -f ./front/Dockerfile . -t ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-front
      - name: Build bff image
        run: docker build -f ./bff/Dockerfile . -t ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-bff
      - name: Push front image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-front
      - name: Push bff image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-bff
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mv -f docker-compose.yml docker-compose.yml
            docker-compose up