name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_VUE_APP_BASE_URI: ${{ secrets.ENV_KEY }}
          directory: ./front

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push bff container
        uses: docker/build-push-action@v3
        with:
          context: ./bff
          file: ./bff/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-bff
      - name: Build and push front container
        uses: docker/build-push-action@v3
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-front
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop pokedex-bff
            docker stop pokedex-front
            docker rm pokedex-front
            docker rm pokedex-bff
            docker rmi kuratovia/pokedex-bff
            docker rmi kuratovia/pokedex-front
            docker pull kuratovia/pokedex-bff
            docker pull kuratovia/pokedex-front
            docker run -d -p 49160:8080 --name=pokedex-bff kuratovia/pokedex-bff
            docker run -d -p 80:80 --name=pokedex-front kuratovia/pokedex-front
      
